// Generated by https://quicktype.io

export interface SegmentCDNSettings {
  integrations:              Integrations;
  plan:                      Plan;
  edgeFunction:              EdgeFunction;
  analyticsNextEnabled:      boolean;
  middlewareSettings:        EdgeFunction;
  enabledMiddleware:         EdgeFunction;
  metrics:                   Metrics;
  legacyVideoPluginsEnabled: boolean;
  remotePlugins:             any[];
}

export interface EdgeFunction {
}

export interface Integrations {
  Mixpanel:                             Mixpanel;
  "Twitter Ads":                        TwitterAds;
  "Tinybird Prod (Ultimatetournament)": TinybirdProdUltimatetournament;
  "Usermachines (Ultimatetournament)":  UsermachinesUltimatetournament;
  "Segment.io":                         SegmentIo;
}

export interface Mixpanel {
  consolidatedPageCalls:       boolean;
  crossSubdomainCookie:        boolean;
  enableEuropeanUnionEndpoint: boolean;
  eventIncrements:             any[];
  groupIdentifierTraits:       any[];
  legacySuperProperties:       boolean;
  people:                      boolean;
  peopleProperties:            any[];
  persistence:                 string;
  propIncrements:              any[];
  secureCookie:                boolean;
  setAllTraitsByDefault:       boolean;
  sourceName:                  string;
  superProperties:             any[];
  token:                       string;
  trackAllPages:               boolean;
  trackCategorizedPages:       boolean;
  trackNamedPages:             boolean;
  versionSettings:             MixpanelVersionSettings;
  type:                        string;
  bundlingStatus:              string;
}

export interface MixpanelVersionSettings {
  version:        string;
  componentTypes: string[];
}

export interface SegmentIo {
  apiKey:                string;
  unbundledIntegrations: string[];
  addBundledMetadata:    boolean;
  maybeBundledConfigIds: MaybeBundledConfigIDS;
  versionSettings:       MixpanelVersionSettings;
  apiHost?: string;
}

export interface MaybeBundledConfigIDS {
  "Twitter Ads":                        string[];
  "Tinybird Prod (Ultimatetournament)": string[];
  "Usermachines (Ultimatetournament)":  string[];
}

export interface TinybirdProdUltimatetournament {
  tableName:       string;
  versionSettings: TinybirdProdUltimatetournamentVersionSettings;
}

export interface TinybirdProdUltimatetournamentVersionSettings {
  componentTypes: any[];
}

export interface TwitterAds {
  events:              Events;
  identifier:          string;
  page:                string;
  universalTagPixelId: string;
  versionSettings:     MixpanelVersionSettings;
  type:                string;
  bundlingStatus:      string;
}

export interface Events {
  "Onboarding TOS Accept Button Clicked": string;
}

export interface UsermachinesUltimatetournament {
  namespace:       string;
  partitions:      string;
  versionSettings: TinybirdProdUltimatetournamentVersionSettings;
}

export interface Metrics {
  sampleRate: number;
}

export interface Plan {
  track:    Track;
  identify: Group;
  group:    Group;
}

export interface Group {
  __default: GroupDefault;
}

export interface GroupDefault {
  enabled: boolean;
}

export interface Track {
  __default: TrackDefault;
}

export interface TrackDefault {
  enabled:      boolean;
  integrations: EdgeFunction;
}
